name: CD - DAST (ZAP Baseline)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# ✅ dá permissão para criar artifacts
permissions:
  contents: read
  actions: write

jobs:
  dast_zap:
    name: DAST - ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # roda a action oficial do ZAP; se ela falhar ao subir artifact interno, seguimos
      - name: Run ZAP Baseline (ignore internal artifact errors)
        id: zap
        uses: zaproxy/action-baseline@v0.12.0
        continue-on-error: true
        with:
          target: "http://testphp.vulnweb.com"
          cmd_options: "-a -j"
          allow_issue_writing: false
          # não dependemos desse artifact interno, mas deixar não atrapalha
          artifact_name: zap

      - name: List generated reports
        run: |
          ls -la
          ls -la report_* || true

      # ✅ nosso upload oficial, com nome único e overwrite
      - name: Upload ZAP reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zapreport-${{ github.run_id }}
          path: |
            report_html.html
            report_json.json
            report_md.md
          overwrite: true
          if-no-files-found: warn
