name: DAST - ZAP Baseline Scan

on:
  workflow_dispatch:

jobs:
  zap-baseline:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Baseline (Docker)
        run: |
          # Desarma o "fail fast" só durante o ZAP, para não quebrar o job por exit code > 0
          set +e
          docker pull ghcr.io/zaproxy/zaproxy:stable -q
          docker run \
            -v "$PWD:/zap/wrk/:rw" \
            --network=host \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t "http://testphp.vulnweb.com" \
              -J report_json.json \
              -w report_md.md \
              -r report_html.html \
              -a -j
          echo "ZAP exit code: $?"
          # Reativa o "fail fast" pro resto da pipeline
          set -e

      - name: List generated files (debug)
        run: |
          ls -la
          ls -la report_* || true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zapreport-${{ github.run_id }}
          path: |
            report_html.html
            report_json.json
            report_md.md
          overwrite: true
          if-no-files-found: error
