name: CD - DAST (ZAP Baseline)

on:
  push:
    branches: [ "main" ]

jobs:
  dast_zap:
    name: DAST - ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ZAP Baseline (Docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zap/wrk/:rw" \
            -t owasp/zap2docker-stable \
            zap-baseline.py \
            -t http://testphp.vulnweb.com \
            -r /zap/wrk/zap_report.html \
            -J /zap/wrk/zap_report.json || true

      - name: Show files in workspace (debug)
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "----"
          find . -maxdepth 3 -type f -name "zap_report*.*" -print

      - name: Upload ZAP report (use wildcard)
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            **/zap_report.html
            **/zap_report.json
