name: CD - DAST (ZAP Baseline)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dast_zap:
    name: DAST - ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Roda a action oficial do ZAP. Se ela falhar ao subir artifact interno,
      # seguimos em frente (vamos fazer nosso próprio upload).
      - name: Run ZAP Baseline (ignore internal artifact errors)
        id: zap
        uses: zaproxy/action-baseline@v0.12.0
        continue-on-error: true
        with:
          target: "http://testphp.vulnweb.com"
          cmd_options: "-a -j"
          allow_issue_writing: false
          # Mesmo se ela tentar criar artifact, não tem problema — não vamos depender disso.
          artifact_name: zapreport

      # Só para conferência no log
      - name: Show generated reports
        run: |
          echo "Workspace files:"
          ls -la
          echo "Expecting these files from ZAP action:"
          ls -la report_* || true

      # Nosso upload oficial (independente da action do ZAP)
      - name: Upload ZAP reports (ours)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zapreport
          path: |
            report_html.html
            report_json.json
            report_md.md
          if-no-files-found: warn
