name: CD - DAST (ZAP Baseline)

on:
  push:
    branches: [ "main" ]

jobs:
  dast_zap:
    name: DAST - ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Rodar ZAP Baseline e salvar relatórios na pasta compartilhada
      - name: Run ZAP Baseline (Docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/zap/wrk/:rw" \
            -t owasp/zap2docker-stable \
            zap-baseline.py \
            -t http://testphp.vulnweb.com \
            -w /zap/wrk/zap_report.html \
            -J /zap/wrk/zap_report.json || true


      # Publicar relatórios como artifact
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap_report.html
            zap_report.json
