name: CD - DAST (ZAP Baseline)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  dast_zap:
    name: DAST - ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Baseline (Docker)
        run: |
          set -e
          # cria arquivos de saída com permissão de escrita
          touch report_json.json report_md.md report_html.html
          chmod a+w report_json.json report_md.md report_html.html

          # roda o ZAP baseline e grava os 3 formatos
          docker pull ghcr.io/zaproxy/zaproxy:stable -q
          docker run \
            -v "$PWD:/zap/wrk/:rw" \
            --network=host \
            -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t "http://testphp.vulnweb.com" \
              -J report_json.json \
              -w report_md.md \
              -r report_html.html \
              -a -j

      - name: List outputs (debug)
        run: |
          ls -la
          ls -la report_* || true

      - name: Upload ZAP reports (artifact único por execução)
        uses: actions/upload-artifact@v4
        with:
          name: zapreport-${{ github.run_id }}
          path: |
            report_html.html
            report_json.json
            report_md.md
          overwrite: true
          if-no-files-found: error
